FROM python:3.9-slim
FROM python:3.9-slim
COPY hello.py .
RUN pip install --upgrade pip && pip install pandas==2.0.3 numpy==1.26.4
RUN pip install pandas==2.0.3 numpy==1.26.4
CMD ["python", "hello.py"]
